# Generated by Django 2.0.6 on 2018-06-26 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_playlisttrack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
