# Generated by Django 2.0.6 on 2018-06-23 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choce',
            new_name='Choice',
        ),
    ]
